backend = "xrender";
fading = true;
fade-delta = 3;
inactive-opacity = 0.88;
active-opacity = 1.0;
inactive-opacity-override = false;

animations = (
  {
    triggers = ["open"];
    opacity = { curve = "cubic-bezier(0.175,0.885,0.32,1.275)"; duration = 0.3; start = 0; end = 1; };
    scale-x = { curve = "cubic-bezier(0.175,0.885,0.32,1.275)"; duration = 0.3; start = 0.7; end = 1; };
    scale-y = { curve = "cubic-bezier(0.175,0.885,0.32,1.275)"; duration = 0.3; start = 0.7; end = 1; };
  },
  {
    triggers = ["close"];
    preset = "disappear"; duration = 0.2; scale = 0.1;
  },
  {
    triggers = ["show"];
    preset = "slide-in"; direction = "right"; duration = 0.25;
  },
  {
    triggers = ["hide"];
    preset = "slide-out"; direction = "right"; duration = 0.2;
  },
  {
    triggers = ["geometry"];
    preset = "geometry-change"; duration = 0.25;
  }
);
