[ -f ~/.xprofile ] && . ~/.xprofile
[ -f ~/.xinitrc.local ] && . ~/.xinitrc.local

xset +fp /usr/share/fonts/misc/ /usr/share/fonts/75dpi/ 2>/dev/null
export XDG_SESSION_TYPE=x11
export XDG_CURRENT_DESKTOP=dwm
/usr/lib/xdg-desktop-portal-gtk &
/usr/lib/xdg-desktop-portal &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

killall picom 2>/dev/null
(slock; picom --vsync --config ~/.config/picom/picom.conf &) &
exec dwm